Fix YCM compilation.

diff --git a/bundles/base/11vim/post-install b/bundles/base/11vim/post-install
--- a/bundles/base/11vim/post-install
+++ b/bundles/base/11vim/post-install
@@ -18,7 +18,7 @@ if [ -d "$YCMDir" ]; then
         if [ ! -f "${YCMDir}/third_party/ycmd/ycm_core.so" -o "${YCMDir}/third_party" -nt "${YCMDir}/third_party/ycmd/ycm_core.so" ]; then
             carapace-message "yellow" "(Re-)compiling YouCompleteMe plugin."
             cd "$YCMDir"
-            python3 install.py --all 1> /dev/null 2> /dev/null || :  # We don't care about failing on this failure
+            python3 install.py --clang-completer --go-completer --java-completer 1> /dev/null 2> /dev/null || :  # We don't care about failing on this failure
         fi
     )
 fi
