Only recompile YCM as necessary (might work)

diff --git a/bundles/base/11vim/post-install b/bundles/base/11vim/post-install
--- a/bundles/base/11vim/post-install
+++ b/bundles/base/11vim/post-install
@@ -14,9 +14,11 @@ vim +PluginClean\! +qall
 YCMDir="${moduledir}/dotfiles/vim/bundle/YouCompleteMe"
 if [ -d "$YCMDir" ]; then
     (
-        carapace-message "yellow" "(Re-)compiling YouCompleteMe plugin."
-        cd "$YCMDir"
-        python3 install.py --clang-completer --go-completer 1> /dev/null || :  # We don't care about failing on this failure
+        if [ ! -f "${YCMDir}/third_party/ycmd/ycm_core.so" -o "${YCMDir}/third_party" -nt "${YCMDir}/third_party/ycmd/ycm_core.so" ]; then
+            carapace-message "yellow" "(Re-)compiling YouCompleteMe plugin."
+            cd "$YCMDir"
+            python3 install.py --all 1> /dev/null 2> /dev/null || :  # We don't care about failing on this failure
+        fi
     )
 fi
 
