Tweaking minimal installation to work better on vreyes machines.

diff --git a/bundles/base/99minimal/bin/carapace-minimal-install-on-host b/bundles/base/99minimal/bin/carapace-minimal-install-on-host
--- a/bundles/base/99minimal/bin/carapace-minimal-install-on-host
+++ b/bundles/base/99minimal/bin/carapace-minimal-install-on-host
@@ -15,7 +15,7 @@ host="$1"
 
 # Make sure that we have a tarball
 if [ ! -r "${generateddir}/carapace-minimal.tar.gz" ]; then
-  >&2 echo "Failed to find Carapace Minimal installation at: '${moduledir}'"
+  >&2 echo "Failed to find Carapace Minimal installation at: '${generateddir}'"
   exit 1
 fi
 
